MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)

# For udev (busybox initcpio [LUKS LVM encryption])
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt lvm2 filesystems fsck)
